# Generated by Django 3.2.9 on 2021-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tokenPush',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='TokenPush'),
        ),
    ]
