# Generated by Django 3.2.9 on 2022-02-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_type_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_persona',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.type_account', verbose_name='Type account'),
        ),
    ]
