# Generated by Django 3.2.9 on 2022-03-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_type_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='longitude'),
        ),
    ]
