# Generated by Django 3.2.9 on 2022-03-04 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0005_auto_20211120_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='%Porcentaje')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisión',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('precio', models.BigIntegerField(verbose_name='Valor')),
                ('fecha_factura', models.DateField(verbose_name='Fecha de factura')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.comision', verbose_name='Comision_factura')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos')),
            ],
            options={
                'verbose_name': 'Facturas',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
