# Generated by Django 3.2.9 on 2022-03-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20220304_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='precio',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
