# Generated by Django 3.2.9 on 2022-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_factura_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ganancia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ganancia'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
