# Generated by Django 3.2.9 on 2021-11-07 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Nombre')),
                ('placa', models.CharField(max_length=100, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('vigencia', models.DateField(blank=True, max_length=100, verbose_name='Vigencia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehiculos')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('persona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_persona', to='account.account')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicios', to='servicios.servicios')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
