# Generated by Django 3.2.9 on 2021-11-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_rename_photo_vehiculo_photovehi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='photovehi',
            new_name='photo',
        ),
    ]
