# Generated by Django 3.2.9 on 2022-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_rename_photovehi_vehiculo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='estado',
            new_name='estado_vehi',
        ),
    ]
