# Generated by Django 3.2.9 on 2022-03-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_rename_estado_vehiculo_estado_vehi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='estado_vehi',
            new_name='estado',
        ),
    ]
