# Generated by Django 3.2.9 on 2022-03-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_sancion'),
        ('servicios', '0001_initial'),
        ('vehiculo', '0007_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_persona', to='account.account'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Servicios', to='servicios.servicios'),
        ),
    ]
