# Generated by Django 3.2.9 on 2021-11-07 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('emision', models.CharField(max_length=256, verbose_name='Recogida')),
                ('destino', models.CharField(max_length=256, verbose_name='Destino')),
                ('indicacion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Indicacion')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('telealt', models.BigIntegerField(blank=True, null=True, verbose_name='Telefono alternativo')),
                ('tiempo', models.IntegerField(blank=True, null=True, verbose_name='Tiempo')),
                ('precio', models.BigIntegerField(blank=True, null=True, verbose_name='Precio')),
                ('solicitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serivicio_solicitud')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account_pedido')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.estado', verbose_name='Estado_pedido')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehiculo_pedido')),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidosActivid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Tiempo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos', verbose_name='Pedido')),
                ('realizado_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Actividades Pedido',
                'verbose_name_plural': 'Actividades Pedido',
            },
        ),
    ]
