# Generated by Django 3.2.9 on 2021-11-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20211108_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='destino',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='emision',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recogida'),
        ),
    ]
