# Generated by Django 3.2.9 on 2021-11-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_ratingaccount_ratingpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingaccount',
            name='obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='ratingpedido',
            name='obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
    ]
