# Generated by Django 3.2.9 on 2022-03-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('pedidos', '0006_alter_pedidos_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='servicios.servicios'),
        ),
    ]
