# Generated by Django 3.2.9 on 2022-04-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='source',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.source', verbose_name='Source_pedido'),
        ),
    ]
