# Generated by Django 3.2.9 on 2022-06-13 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedidos_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
