# Generated by Django 3.2.9 on 2022-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedidos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='solicitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio_solicitud'),
        ),
    ]
